/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import javax.swing.JOptionPane;

/**
 *
 * @author Lasitha Ranawaka
 */
public class template extends javax.swing.JDialog {

    /**
     * Creates new form template
     */
    public template(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
      String a = "", a1 = "", b = "", b1 = "", d = "", ce = "", g = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chk_A = new javax.swing.JCheckBox();
        chk_B = new javax.swing.JCheckBox();
        chk_B1 = new javax.swing.JCheckBox();
        chk_D = new javax.swing.JCheckBox();
        chk_A1 = new javax.swing.JCheckBox();
        chk_CE = new javax.swing.JCheckBox();
        chk_G = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);

        chk_A.setText("A");
        chk_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_AActionPerformed(evt);
            }
        });

        chk_B.setText("B");
        chk_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_BActionPerformed(evt);
            }
        });

        chk_B1.setText("B1");
        chk_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_B1ActionPerformed(evt);
            }
        });

        chk_D.setText("D");
        chk_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_DActionPerformed(evt);
            }
        });

        chk_A1.setText("A1");
        chk_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_A1ActionPerformed(evt);
            }
        });

        chk_CE.setText("CE");
        chk_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_CEActionPerformed(evt);
            }
        });

        chk_G.setText("G");
        chk_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_GActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_A1)
                    .addComponent(chk_A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_CE)
                    .addComponent(chk_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_B1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_D)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1))
                    .addComponent(chk_G))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_A)
                    .addComponent(chk_B)
                    .addComponent(chk_B1)
                    .addComponent(chk_D)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_A1)
                    .addComponent(chk_CE)
                    .addComponent(chk_G))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      

        if (chk_A.isSelected()) {
            a = "A ";
        }
        if (chk_A1.isSelected()) {
            a1 = "A1 ";
        }
        if (chk_B.isSelected()) {
            b = "B ";
        }
        if (chk_B1.isSelected()) {
            b1 = "B1 ";
        }
        if (chk_D.isSelected()) {
            d = "D ";
        }
        if (chk_CE.isSelected()) {
            ce = "CE ";
        }
        if (chk_G.isSelected()) {
            g = "G ";
        }

       String vc =  a + a1 + b + b1 + d + ce + g;
        JOptionPane.showMessageDialog(null, vc, "Vehicle classes" , JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void chk_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_AActionPerformed
        

       
    }//GEN-LAST:event_chk_AActionPerformed

    private void chk_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_BActionPerformed
       
    }//GEN-LAST:event_chk_BActionPerformed

    private void chk_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_B1ActionPerformed
       
    }//GEN-LAST:event_chk_B1ActionPerformed

    private void chk_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_DActionPerformed
       
    }//GEN-LAST:event_chk_DActionPerformed

    private void chk_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_A1ActionPerformed
       
    }//GEN-LAST:event_chk_A1ActionPerformed

    private void chk_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_CEActionPerformed
       
    }//GEN-LAST:event_chk_CEActionPerformed

    private void chk_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_GActionPerformed
        
    }//GEN-LAST:event_chk_GActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                template dialog = new template(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_A;
    private javax.swing.JCheckBox chk_A1;
    private javax.swing.JCheckBox chk_B;
    private javax.swing.JCheckBox chk_B1;
    private javax.swing.JCheckBox chk_CE;
    private javax.swing.JCheckBox chk_D;
    private javax.swing.JCheckBox chk_G;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
